# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(664, 338)
        MainWindow.setStyleSheet("*:disabled {\n"
"    background-color:rgb(30, 30, 30);    \n"
"    color: rgb(127, 127, 127);\n"
"}\n"
"*{\n"
"    background-color: rgb(90, 90, 90);\n"
"    color: white;\n"
"}\n"
"QLabel:disabled {\n"
"    background-color: rgb(90, 90, 90);\n"
"}\n"
"QGroupBox{\n"
"    border: 1px solid rgb(70, 70, 70);\n"
"    margin-top: 1em;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QGroupBox:disabled {\n"
"    background-color: rgb(90, 90, 90);\n"
"}\n"
"QGroupBox::title {\n"
"    background-color: rgb(90, 90, 90);\n"
"        top: -0.8em;\n"
"        left: 1em;\n"
"}\n"
"QMenu::item{\n"
"    background-color: rgb(90, 90, 90);\n"
"    color: white;\n"
"}\n"
"\n"
"QMenuBar::item:selected{\n"
"    color: cyan;\n"
"}\n"
"QMenu::item:selected {\n"
"    color: cyan;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_7.addWidget(self.comboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.btnRefresh = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnRefresh.setFont(font)
        self.btnRefresh.setObjectName("btnRefresh")
        self.horizontalLayout_6.addWidget(self.btnRefresh)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8.addWidget(self.groupBox_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.rpu = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.rpu.setFont(font)
        self.rpu.setObjectName("rpu")
        self.verticalLayout.addWidget(self.rpu)
        self.xpu = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.xpu.setFont(font)
        self.xpu.setObjectName("xpu")
        self.verticalLayout.addWidget(self.xpu)
        self.bpu = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bpu.setFont(font)
        self.bpu.setObjectName("bpu")
        self.verticalLayout.addWidget(self.bpu)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_r = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbl_r.setFont(font)
        self.lbl_r.setObjectName("lbl_r")
        self.verticalLayout_2.addWidget(self.lbl_r)
        self.lbl_x = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbl_x.setFont(font)
        self.lbl_x.setObjectName("lbl_x")
        self.verticalLayout_2.addWidget(self.lbl_x)
        self.lbl_b = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbl_b.setFont(font)
        self.lbl_b.setObjectName("lbl_b")
        self.verticalLayout_2.addWidget(self.lbl_b)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addWidget(self.groupBox_2)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 664, 21))
        self.menubar.setObjectName("menubar")
        self.menuImport_Export = QtWidgets.QMenu(self.menubar)
        self.menuImport_Export.setObjectName("menuImport_Export")
        self.menuCreate = QtWidgets.QMenu(self.menubar)
        self.menuCreate.setObjectName("menuCreate")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionTxt_to_json = QtWidgets.QAction(MainWindow)
        self.actionTxt_to_json.setObjectName("actionTxt_to_json")
        self.actionJson_to_txt = QtWidgets.QAction(MainWindow)
        self.actionJson_to_txt.setObjectName("actionJson_to_txt")
        self.actionMake_F_le = QtWidgets.QAction(MainWindow)
        self.actionMake_F_le.setObjectName("actionMake_F_le")
        self.actionDisplay_online_documentation = QtWidgets.QAction(MainWindow)
        self.actionDisplay_online_documentation.setObjectName("actionDisplay_online_documentation")
        self.actionOffline_help = QtWidgets.QAction(MainWindow)
        self.actionOffline_help.setObjectName("actionOffline_help")
        self.menuImport_Export.addAction(self.actionTxt_to_json)
        self.menuImport_Export.addAction(self.actionJson_to_txt)
        self.menuCreate.addAction(self.actionMake_F_le)
        self.menuHelp.addAction(self.actionDisplay_online_documentation)
        self.menuHelp.addAction(self.actionOffline_help)
        self.menubar.addAction(self.menuCreate.menuAction())
        self.menubar.addAction(self.menuImport_Export.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Transmission Line Parameters Calculator"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Input"))
        self.btnRefresh.setText(_translate("MainWindow", "Refresh list"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Results"))
        self.groupBox.setTitle(_translate("MainWindow", "Per unit"))
        self.rpu.setText(_translate("MainWindow", "R_pu: --- pu"))
        self.xpu.setText(_translate("MainWindow", "X_pu: --- pu"))
        self.bpu.setText(_translate("MainWindow", "B_pu: --- pu"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Actual"))
        self.lbl_r.setText(_translate("MainWindow", "R: --- Ω"))
        self.lbl_x.setText(_translate("MainWindow", "X: --- Ω"))
        self.lbl_b.setText(_translate("MainWindow", "B: --- S"))
        self.menuImport_Export.setTitle(_translate("MainWindow", "Import/Export"))
        self.menuCreate.setTitle(_translate("MainWindow", "Create"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionTxt_to_json.setText(_translate("MainWindow", "Txt to json"))
        self.actionJson_to_txt.setText(_translate("MainWindow", "Json to txt"))
        self.actionMake_F_le.setText(_translate("MainWindow", "Make Fİle"))
        self.actionDisplay_online_documentation.setText(_translate("MainWindow", "Online documentation"))
        self.actionOffline_help.setText(_translate("MainWindow", "Offline help"))
